services:
  baselinker.command.test.test:
    class: SyliusBaselinkerPlugin\Command\TestCommand
    arguments:
    tags: ["console.command"]

  baselinker.command.orders.add:
    class: SyliusBaselinkerPlugin\Command\OrdersAddCommand
    arguments:
      - "@baselinker.repository.order"
      - "@baselinker.service.orders_api"
      - "@doctrine.orm.default_entity_manager"
      - "@monolog.logger.baselinker"
    tags: ["console.command"]

  baselinker.command.orders.payments:
    class: SyliusBaselinkerPlugin\Command\OrdersPaymentsCommand
    arguments:
      - "@baselinker.repository.order"
      - "@baselinker.service.orders_api"
      - "@doctrine.orm.default_entity_manager"
    tags: ["console.command"]

  baselinker.command.orders.statuses:
    class: SyliusBaselinkerPlugin\Command\OrdersStatusCommand
    arguments:
      - "@sylius.repository.order"
      - "@baselinker.service.orders_api"
      - "@doctrine.orm.default_entity_manager"
      - "@baselinker.service.order_status_applier"
    tags: ["console.command"]
