services:
  baselinker.command.test.test:
    class: SyliusBaselinkerPlugin\Command\TestCommand
    arguments:
    tags: ["console.command"]

  baselinker.command.order.sync:
    class: SyliusBaselinkerPlugin\Command\OrdersSyncCommand
    arguments:
      - "@sylius.repository.order"
      - "@baselinker.service.orders_api"
      - "@doctrine.orm.default_entity_manager"
      - "@baselinker.service.order_status_applier"
    tags: ["console.command"]
