services:
  baselinker.grid_field.status_connected:
    class: SyliusBaselinkerPlugin\Grid\FieldType\StatusConnectedType
    arguments:
      - '@baselinker.service.orders_api'
    tags:
        - { name: sylius.grid_field, type: status_connected }

  baselinker.grid_field.settings:
    class: SyliusBaselinkerPlugin\Grid\FieldType\SettingsType
    arguments:
      - '@baselinker.service.orders_api'
    tags:
        - { name: sylius.grid_field, type: settings }

  baselinker.grid_field.translatable_string:
    class: SyliusBaselinkerPlugin\Grid\FieldType\TranslatableStringType
    arguments:
      - '@translator.data_collector'
      - '@sylius.grid.data_extractor'
    tags:
        - { name: sylius.grid_field, type: translatable_string }
