services:
  baselinker.serializer.order:
    class: SyliusBaselinkerPlugin\Serializer\OrderSerializer
    public: true
    arguments:
      - "@baselinker.data_provider.order"
      - "@baselinker.data_provider.order_item"
      - "@baselinker.data_provider.payment"
