imports:
    - { resource: "@SyliusBaselinkerPlugin/src/Resources/config/packages/resources.yml" }
    - { resource: "@SyliusBaselinkerPlugin/src/Resources/config/packages/grids.yml" }

sylius_baselinker:
    token: "%env(string:BL_TOKEN)%"
    url: https://api.baselinker.com/connector.php
    method: POST
