sylius_grid:
    grids:
        baselinker_admin_settings:
            driver:
                name: doctrine/orm
                options:
                    class: SyliusBaselinkerPlugin\Entity\Settings
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                value:
                    type: string
                    label: sylius.ui.value
            actions:
                item:
                    update:
                        type: update

        baselinker_admin_statuses:
            driver:
                name: doctrine/orm
                options:
                    class: SyliusBaselinkerPlugin\Entity\StatusesAssociations
            fields:
                shopStatus:
                    type: string
                    label: baselinker.ui.shop_status
                baselinkerStatus:
                    type: string
                    label: baselinker.ui.baselinker_status
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
