sylius_resource:
    resources:
        baselinker.settings:
            driver: doctrine/orm
            classes:
                model: SyliusBaselinkerPlugin\Entity\Settings
                form: SyliusBaselinkerPlugin\Form\Type\SettingsType

        baselinker.statuses:
            driver: doctrine/orm
            classes:
                model: SyliusBaselinkerPlugin\Entity\StatusesAssociations
                form: SyliusBaselinkerPlugin\Form\Type\StatusesAssociationsType
