sylius_resource:
    resources:
        baselinker.settings:
            driver: doctrine/orm
            classes:
                model: SyliusBaselinkerPlugin\Entity\BaselinkerSettings
                form: SyliusBaselinkerPlugin\Form\Type\BaselinkerSettingsType
                repository: SyliusBaselinkerPlugin\Repository\BaselinkerSettingsRepository
