sylius_resource:
    resources:
        baselinker.settings:
            driver: doctrine/orm
            classes:
                model: SyliusBaselinkerPlugin\Model\BaselinkerSettings
                form: SyliusBaselinkerPlugin\Form\Type\BaselinkerSettingsType
                repository: SyliusBaselinkerPlugin\Repository\BaselinkerSettingsRepository

        baselinker.statuses:
            driver: doctrine/orm
            classes:
                model: SyliusBaselinkerPlugin\Model\BaselinkerStatusesAssociations
                form: SyliusBaselinkerPlugin\Form\Type\BaselinkerStatusesAssociationsType
