baselinker_admin_settings_index:
    resource: |
        alias: baselinker.settings
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: baselinker_admin_settings
        vars:
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin