imports:
  - { resource: "@SyliusBaselinkerPlugin/Resources/config/packages/baselinker.yml" }
  - { resource: "@SyliusBaselinkerPlugin/Resources/config/packages/resources.yml" }
  - { resource: "@SyliusBaselinkerPlugin/Resources/config/packages/grids.yml" }
