services:

    sylius.baselinker.plugin:
        class: SyliusBaselinkerPlugin\Command\TestCommand
        arguments:
        tags: ['console.command']
        

    baselinker.api.request.service:
        class: SyliusBaselinkerPlugin\Services\BaselinkerApiRequestService
        arguments:
        - '@Symfony\Contracts\HttpClient\HttpClientInterface'
        - '%sylius.baselinker_token%'
        - '%sylius.baselinker_url%'
        - '%sylius.baselinker_method%'

    baselinker.orders.api.service:
        class: SyliusBaselinkerPlugin\Services\BaselinkerOrdersApiService
        arguments:
        - '@baselinker.api.request.service'

    baselinker.serializers.serializer:
        class: SyliusBaselinkerPlugin\Serializers\BaselinkerSerializer
        arguments:
        - '@baselinker.subscribers.handler_subscriber'
        - '@baselinker.subscribers.event_subscriber'
        - '@SyliusBaselinkerPlugin/Resources/config/serializer'

    baselinker.subscribers.event_subscriber:
        class: SyliusBaselinkerPlugin\Subscribers\BaselinkerEventSubscriber
        arguments:
        - '@sylius.tax_rate_resolver'

    baselinker.subscribers.handler_subscriber:
        class: SyliusBaselinkerPlugin\Subscribers\BaselinkerHandlerSubscriber

    baselinker.subscribers.admin.menu_builder:
        class: SyliusBaselinkerPlugin\Subscribers\BaselinkerAdminMenuSubscriber
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuEntries }