services:

    sylius.baselinker.plugin:
        class: SyliusBaselinkerPlugin\Command\TestCommand
        arguments:
        tags: ['console.command']
        
    baselinker.api.request.service:
        class: SyliusBaselinkerPlugin\Services\BaselinkerApiRequestService
        arguments:
        - '@Symfony\Contracts\HttpClient\HttpClientInterface'
        - '%sylius.baselinker_token%'
        - '%sylius.baselinker_url%'
        - '%sylius.baselinker_method%'

    baselinker.orders.api.service:
        class: SyliusBaselinkerPlugin\Services\BaselinkerOrdersApiService
        arguments:
        - '@baselinker.api.request.service'

    baselinker.serializers.serializer:
        class: SyliusBaselinkerPlugin\Serializers\BaselinkerSerializer
        arguments:
        - '@baselinker.subscribers.handler_subscriber'
        - '@baselinker.subscribers.event_subscriber'
        - 'src/Resources/config/serializer'

    baselinker.subscribers.event_subscriber:
        class: SyliusBaselinkerPlugin\Subscribers\BaselinkerEventSubscriber
        arguments:
        - '@sylius.tax_rate_resolver'
        - '@doctrine.orm.default_entity_manager'

    baselinker.subscribers.handler_subscriber:
        class: SyliusBaselinkerPlugin\Subscribers\BaselinkerHandlerSubscriber

    baselinker.subscribers.admin.menu_builder:
        class: SyliusBaselinkerPlugin\Subscribers\BaselinkerAdminMenuSubscriber
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuEntries }

    baselinker.settings.form.type:
        class: SyliusBaselinkerPlugin\Form\Type\BaselinkerSettingsType
        tags:
            - { name: form.type }
        arguments: 
        - 'SyliusBaselinkerPlugin\Entity\BaselinkerSettings'
        - '@baselinker.orders.api.service'

    baselinker.statuses.associations.form.type:
        class: SyliusBaselinkerPlugin\Form\Type\BaselinkerStatusesAssociationsType
        tags:
            - { name: form.type }
        arguments: 
        - 'SyliusBaselinkerPlugin\Entity\BaselinkerStatusesAssociations'
        - '@baselinker.orders.api.service'
