imports:
    - { resource: "../../../tests/Fixtures/sylius_fixtures/*.yml" }

services:
    _defaults:
        public: true

    Doctrine\ORM\EntityManagerInterface:
        public: true

    SyliusBaselinkerPlugin\Resolver\StatusResolver:
        autowire: true
