imports:
  - { resource: "services/*.yml" }

services:
    sylius.baselinker.plugin:
        class: SyliusBaselinkerPlugin\Command\TestCommand
        arguments:
        tags: ['console.command']
        
    baselinker.api.request.service:
        class: SyliusBaselinkerPlugin\Services\BaselinkerApiRequestService
        arguments:
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'
            - "%sylius.baselinker_token%"
            - "%sylius.baselinker_url%"
            - "%sylius.baselinker_method%"

    baselinker.orders.api.service:
        class: SyliusBaselinkerPlugin\Services\BaselinkerOrdersApiService
        arguments:
            - "@baselinker.api.request.service"
            - "@baselinker.serializers.serializer"

    baselinker.serializers.serializer:
        class: SyliusBaselinkerPlugin\Serializers\BaselinkerSerializer
        public: true
        arguments:
            - "@baselinker.data_provider.order"
            - "@baselinker.data_provider.order_item"

    baselinker.subscribers.admin.menu_builder:
        class: SyliusBaselinkerPlugin\Subscribers\BaselinkerAdminMenuSubscriber
        tags:
            - {
                  name: kernel.event_listener,
                  event: sylius.menu.admin.main,
                  method: addAdminMenuEntries,
              }

    baselinker.settings.form.type:
        class: SyliusBaselinkerPlugin\Form\Type\BaselinkerSettingsType
        tags:
            - { name: form.type }
        arguments:
            - 'SyliusBaselinkerPlugin\Entity\BaselinkerSettings'
            - "@baselinker.orders.api.service"

    baselinker.statuses.associations.form.type:
        class: SyliusBaselinkerPlugin\Form\Type\BaselinkerStatusesAssociationsType
        tags:
            - { name: form.type }
        arguments:
            - 'SyliusBaselinkerPlugin\Entity\BaselinkerStatusesAssociations'
            - "@baselinker.orders.api.service"

    baselinker.data_provider.order:
        class: SyliusBaselinkerPlugin\DataProviders\BaselinkerOrderDataProvider
        arguments:
            - "@doctrine.orm.default_entity_manager"

    baselinker.data_provider.order_item:
        class: SyliusBaselinkerPlugin\DataProviders\BaselinkerOrderItemDataProvider
        arguments:
            - "@sylius.tax_rate_resolver"

    baselinker.form.extension.type.order:
        class: SyliusBaselinkerPlugin\Form\Extension\OrderTypeExtension
        tags:
            - { 
                name: form.type_extension,
                extended_type: Sylius\Bundle\OrderBundle\Form\Type\OrderType,
                extended-type: Sylius\Bundle\OrderBundle\Form\Type\OrderType,
                priority: 110,
                }
