Sylius\Component\Addressing\Model\Address:
  virtual_properties:
    
    #fullname
    getFullName:
      serialized_name: fullname
      groups: [bl]

  properties:

    #company
    company:
      groups: [bl]
    
    #address
    street:
      serialized_name: address
      groups: [bl]

    #postcode
    postcode:
      groups: [bl]

    #city
    city:
      groups: [bl]

    #state
    provinceName:
      serialized_name: state
      groups: [bl]

    #country_code
    countryCode:
      groups: [bl]
