Sylius\Component\Core\Model\OrderItem:
# storage (varchar) - type of magazine from which the product comes (available values: "db" - BaseLinker internal catalog, "shop" - the online store magazine, "warehouse" - a connected wholesaler).
# storage_id (int) - the identifier of the magazine from which the product comes (one of the shops connected to the account). Value "0" for a product from the BaseLinker internal catalog.
# product_id (varchar) - Product identifier in BaseLinker or store magazine. Blank if the product number is unknown
# variant_id (int) - Product variant ID. Blank if the variant number is unknown
# sku (varchar) - Product sku
# ean (varchar) - Product ean
# location (varchar) - Product location
# warehouse_id (int) - Product source warehouse identifier. Only applies to products from BaseLinker inventory. By default warehouse_id is determined based on the source of the order.

  properties:
    #name
    productName:
      serialized_name: name
      groups: [bl]

    #attributes
    variantName:
      serialized_name: attributes
      groups: [bl]

    variant:
      inline: true
      groups: [bl]
